### ISSUE TITLE
Develop upgrade procedure for gluu-snap

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/gluu-snap#23]
Most parts of gluu-snap package is read only. We need an upgrade procedure for gluu-snap package.

**Comment by adrian-gluu** [comment]
@mbaser I think snap refresh after push 4.2.x into snapcraft store it will do the magic for us it will preserv modified data and it will keep the old one doing an snapshot, and you can roll back to previous release after snap snapshot the old one

**Comment by mbaser** [comment]
4.1.1 to 4.2.1 upgrade was implemented
