### ISSUE TITLE
no chroot

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/gluu-snap#4]
When I run jython and try to list root dir and /opt, it gives list of host system. Not sure if application running inside sees as this. If so every source packages should be edited. This is huge number of works.

```
$ gluu-server.jython 
Jython 2.7.2rc1 (v2.7.2rc1:1fcef1abf1d6, Mar 1 2020, 16:27:06)
[OpenJDK 64-Bit Server VM (Amazon.com Inc.)] on java1.8.0_222
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.listdir('/')
['bin', 'boot', 'dev', 'etc', 'home', 'lib', 'lib64', 'media', 'meta', 'mnt', 'opt', 'proc', 'root', 'run', 'sbin', 'snap', 'srv', 'sys', 'tmp', 'usr', 'var', 'writable']
>>> os.listdir('/var')
['backups', 'cache', 'home', 'lib', 'lock', 'log', 'mail', 'opt', 'run', 'snap', 'spool', 'tmp']
>>> os.listdir('/var/opt')
[]
```

These listing are host file system, not snap package

**Comment by mbaser** [comment]
From this document https://github.com/snapcore/snapd/wiki/Snap-Execution-Environment#setting-up-the-mount-namespace
*The application sees the core snap as the root of the file system. You can think of this as a chroot of sort.*

**Comment by mbaser** [comment]
I created a simple flask app that returns directory listing. Unfortunately, it sees host file system
![Screenshot_2020-03-18_19-20-17](https://user-images.githubusercontent.com/6398752/76982959-acc1c600-694d-11ea-9978-63d2a818499b.png)

Here it is content of directory `/snap` on host file system

**Comment by mbaser** [comment]
We can overcome this issue by using layouts as follows:

```
passthrough:
  layout:
    /opt:
      bind: $SNAP/opt
```
So that applications inside sees `/opt` directory as we intend. But in this case, snapcfrat denies to build the following app:

```
  jython:
    environment:
      JAVA_HOME: "/opt/jre"
    command: /opt/jre/bin/java  -jar /opt/jython/jython.jar
```

The error is:
```
    with open(exepath, "rb") as exefile:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/jre/bin/java'
We would appreciate it if you created a bug report at
https://launchpad.net/snapcraft/+filebug with the above text included.
```

**Comment by mbaser** [comment]
`/opt` layout seems wrong approach, it seems we can overcome this with:

```
  layout:
    /opt/gluu:
      bind: $SNAP/opt/gluu
```

So we need only `/opt/gluu` and other directories to be bind

**Comment by mbaser** [comment]
Linking only `/opt/gluu` seems to work, but there may be some code looking `/opt`, for example most probably gluu war files seeks `/opt/jython/jython.jar`

I propose
* put files `/gluu-opt`
* link `gluu-opt` to `/opt/`

**Comment by mbaser** [comment]
This proposition works, but there is another issue, we can't make any link under `/opt`, for example this failed

```
  layout:

    /opt:
      bind: $SNAP/gluu-opt
    /opt/gluu/jetty/oxauth/oxauth.state:
      symlink: $SNAP_COMMON/gluu/jetty/oxauth/oxauth.state
```

**Comment by mbaser** [comment]
Instead of global link (`/opt`), individual link seems to work:
```
  layout:
    /opt/jre:
      symlink: $SNAP/gluu-opt/amazon-corretto-8.222.10.1-linux-x64
    /opt/gluu/jetty/oxauth/oxauth.state:
      symlink: $SNAP_COMMON/gluu/jetty/oxauth/oxauth.state
```

But jython failed to list directories:
```
>>> os.listdir('/opt/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: listdir(): an unknown error occurred: /opt/
```
But this is working:

```
>>> os.listdir('/opt/jre')
['ASSEMBLY_EXCEPTION', 'LICENSE', 'THIRD_PARTY_README', 'bin', 'etc', 'include', 'javafx-src.zip', 'jre', 'lib', 'man', 'src.zip', 'usr', 'var', 'version.txt']

```

**Comment by adrian-gluu** [comment]
We have a plan and we are going to a different approach non of these issues are need it.

**Comment by alvesadrian** [comment]
I will close al this issue we have a plan with task
