### ISSUE TITLE
links in override-prime section are incorrect

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/gluu-snap#6]
For example the following link are incorrect:
```
ln -s $SNAPCRAFT_PRIME/gluu-opt/amazon-corretto-8.222.10.1-linux-x64 $SNAPCRAFT_PRIME/gluu-opt/jre
```

They should be arranged in `layout` section

**Comment by mbaser** [comment]
Proposed method causes build error

**Comment by adrian-gluu** [comment]
We have a plan and we are going to a different approach non of these issues are need it.
