### ISSUE TITLE
setup.py inside of the snap

### ISSUE THREAD

**Issue by adrian-gluu** [GluuFederation/gluu-snap#9]
@mbaser figure how to run or how is the behaviour  of setup.py as per user doc is inside of the confident and tweak the writeable dirs need it on setup.py

**Comment by mbaser** [comment]
This is just a description. Not an issue. Please be specific.

**Comment by mbaser** [comment]
Some part of setup.py should be moved to snapcraft.yaml and to hooks.
 @adrian-gluu determine which parts are going to be implemented in snapcraft.yaml and in hooks and move to there

**Comment by adrian-gluu** [comment]
I will start handling the services setup daemons files and of course  files raleted with those from inside of setup.py.
You can start with path that need to be writeable for user conf

**Comment by mbaser** [comment]
Without having a package how can i do this?
>You can start with path that need to be writeable for user conf

**Comment by mbaser** [comment]
done
